version: "3"
services:

#https://hub.docker.com/r/rocker/rstudio

  rstudio:
    image: rocker/rstudio
    ports:
      - "8787:8787"
    environment:
      - USER=rstudio
      - PASSWORD=123456
    volumes:
          - "./scripts:/home/rstudio/scripts"
          - "./data:/home/rstudio/data"
